# Generated by Django 3.1.1 on 2021-04-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
