# Generated by Django 3.0.5 on 2021-03-25 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
